{
	"name": "Fabric",
	"on": {
		"push": {
			"branches": [
				"master"
			]
		},
		"pull_request": {
			"branches": [
				"master"
			]
		}
	},
	"jobs": {
		"buildMod": {
			"name": "Build mod",
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2.1.0"
				},
				{
					"uses": "actions/setup-java@v1.3.0",
					"with": {
						"java-version": 8
					}
				},
				{
					"uses": "eskatos/gradle-command-action@v1",
					"with": {
						"gradle-version": "current",
						"arguments": "build"
					}
				},
				{
					"uses": "actions/upload-artifact@v1.0.0",
					"with": {
						"name": "Builds",
						"path": "build/libs"
					}
				}
			]
		}
	}
}
