{
    "name": "Fabric",
    "on": [
        "push",
        "pull_request"
    ],
    "jobs": {
        "buildMod": {
            "name": "Build mod",
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "name": "Checkout",
                    "uses": "actions/checkout@v2.1.0"
                },
                {
                    "name": "Set up Java 8",
                    "uses": "actions/setup-java@v1.3.0",
                    "with": {
                        "java-version": 8
                    }
                },
                {
                    "name": "Set up Gradle",
                    "uses": "eskatos/gradle-command-action@v1",
                    "with": {
                        "gradle-version": "current"
                    }
                },
                {
                    "name": "Build mod",
                    "uses": "eskatos/gradle-command-action@v1",
                    "with": {
                        "arguments": "build"
                    }
                },
                {
                    "name": "Upload mod artifacts",
                    "uses": "actions/upload-artifact@v1.0.0",
                    "with": {
                        "name": "Builds",
                        "path": "build/libs"
                    }
                }
            ]
        }
    }
}
